package com.example.demo.exception.specific

class ErrorCode {
    companion object {
        const val BANK_LOAN_TYPE_NAME_ALREADY_EXISTS_ERROR = "BANK_LOAN_TYPE_NAME_ALREADY_EXISTS_ERROR"
        const val BANK_LOAN_TYPE_DOES_NOT_EXIST_ERROR = "BANK_LOAN_DOES_NOT_EXIST_ERROR"
        const val LOAN_REQUEST_DOES_NOT_EXISTS_ERROR = "LOAN_REQUEST_DOES_NOT_EXISTS_ERROR"
        const val LOAN_REQUEST_STEP_DOES_NOT_EXISTS_ERROR = "LOAN_REQUEST_STEP_DOES_NOT_EXISTS_ERROR"
        const val LOAN_REQUEST_STEP_STATUS_CHANGE_ERROR = "LOAN_REQUEST_STEP_STATUS_CHANGE_ERROR"
        const val PREVIOUS_STEPS_NOT_SUCCESSFUL_ERROR = "PREVIOUS_STEPS_NOT_SUCCESSFUL_ERROR"
        const val LOAN_REQUEST_FOR_BANK_LOAN_TYPE_EXISTS_ERROR = "LOAN_REQUEST_FOR_BANK_LOAN_TYPE_EXISTS_ERROR"
        const val UNKNOWN_ERROR = "UNKNOWN_ERROR"
    }
}