services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - test
  spring-app:
    image: demo-app
    networks:
      - test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/postgres
    ports:
      - '8080:8080'
networks:
  test:
    driver: bridge
volumes:
  db: